-- Create a table for storing inquiries
create table inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  facility_name text not null,
  company_name text,
  contact_name text not null,
  email text not null,
  phone text not null,
  inquiry_type text not null,
  message text
);

-- Set up Row Level Security (RLS)
-- For now, we allow public insert (for the form) but restrict read to authenticated users (admin)
alter table inquiries enable row level security;

create policy "Enable insert for public" on inquiries
  for insert with check (true);

create policy "Enable read for authenticated users only" on inquiries
  for select using (auth.role() = 'authenticated');
